### ISSUE TITLE
Won't update, but it is out-of-date

### ISSUE THREAD

**Issue by rffontenelle** [ushis/local-repo#54] opened 2012-04-25 02:14 UTC
I have some packages in this situations, but I haven't figure out what is the pattern. As a workaround I remove and add again to the repo db.

See an example:

$ LC_ALL=C lr -s lib32-glib-networking

> Loading repo: /var/cache/rafaelrepo
> lib32-glib-networking 2.30.2-1

$ LC_ALL=C yaourt -Ss lib32-glib-networking
rafaelrepo/lib32-glib-networking 2.30.2-1
    Network-related giomodules for glib (32 bit)
aur/lib32-glib-networking 2.32.1-1 (5)
    Network-related giomodules for glib (32 bit)

$ LC_ALL=C lr -U

> Loading repo: /var/cache/rafaelrepo
> 254 packages found
> Retrieving package info from the AUR
> 82 packages found
> Checking for updates
> All packages are up to date

**Comment by ushis** [comment] 2012-04-25 04:48
Hmm, i couldnt reproduce this issue. A few questions...
- Is this package listed in your config in the **no-aur-upgrade** list?
- What python version are you running?
- Can you test this in your python shell please?
  
  ```
  $ python
  >>> from distutils.version import LooseVersion
  >>> LooseVersion('2.30.2-1') < LooseVersion('2.32.1-1')
  True
  ```
- Is it possible to upload your database somewhere? Dropbox or something..

And a tip: A simpler workauround is using the **-fA** switches.

**Comment by rffontenelle** [comment] 2012-04-25 05:30
1) I did not set no-aur-upgrade

2) Currently I have python version 3.2.3, but most likely the package was added in version 3.2.2. Can't be sure, though.

3) Output was "True".

4) http://dl.dropbox.com/u/19823921/rafaelrepo.db.tar.gz

Your tip worked perfectly. BTW, I should read more often the '--help', as I was using '-a' to download from AUR with srctarball (so difficult!). Thanks for the lesson!

**Comment by ushis** [comment] 2012-04-25 10:42
hmm, this is so strange... i ran some tests and suspect that there is a limit of arguments the AUR RPC is able/willing to handle. So you dont get all the package info you want. local-repo just _thinks_ that _lib32-glib-networking_ is no AUR package, because the AUR sends no information about it.

**Comment by ushis** [comment] 2012-04-26 07:13
@josephgbr Please checkout the **split-requests** branch and test it again. local-repo splits the number of packages in chunks of the size of 50 now and sends multiple requests to the AUR. If this works well, i will look, how i can speed this up.

**Comment by ushis** [comment] 2012-04-27 05:43
This works well now. Its been merged into devel.

**Closed as completed by ushis** 2012-04-27 05:43 UTC
